/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HakkindaImport } from './routes/hakkinda'

// Create/Update Routes

const HakkindaRoute = HakkindaImport.update({
  path: '/hakkinda',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hakkinda': {
      id: '/hakkinda'
      path: '/hakkinda'
      fullPath: '/hakkinda'
      preLoaderRoute: typeof HakkindaImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ HakkindaRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/hakkinda"
      ]
    },
    "/hakkinda": {
      "filePath": "hakkinda.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
